export const PageHeader: string
export const pageHeader: string
export const LogoFull: string
export const logoFull: string
export const Announcement: string
export const announcement: string
export const AnnouncementLayout: string
export const announcementLayout: string
export const skeletonShimmerAnimation: string
