export const MediaCard: string;
export const mediaCard: string;
export const MediaCardUpper: string;
export const mediaCardUpper: string;
export const MediaCardLower: string;
export const mediaCardLower: string;
export const MediaCardIcon: string;
export const mediaCardIcon: string;
export const skeletonShimmerAnimation: string;
