export const Text: string
export const text: string
export const Link: string
export const link: string
export const Tag: string
export const tag: string
export const typeTechLink: string
export const isLight: string
export const isMedium: string
export const isBold: string
export const typeFooterTitle: string
export const typeFooterText: string
export const typeFooterContact: string
export const typeFooterMessage: string
export const typeMediaCardTitle: string
export const typeMediaCardText: string
export const typeMediaCardTextLink: string
export const typeLinkCardHeader: string
export const typeLinkCardText: string
export const typeLinkCardFooter: string
export const typeLinkCardLink: string
export const typeVisionHeading: string
export const typeQuoteText: string
export const typeQuoteAuthor: string
export const typeQuoteRole: string
export const typeContactHeader: string
export const typeStat: string
export const typeBioLink: string
export const isInverse: string
export const isInk: string
export const skeletonShimmerAnimation: string
