export const Card: string
export const card: string
export const CardLinks: string
export const cardLinks: string
export const CardIcon: string
export const cardIcon: string
export const CardIconThird: string
export const cardIconThird: string
export const isActive: string
export const skeletonShimmerAnimation: string
