export const Card: string
export const card: string
export const CardHeader: string
export const cardHeader: string
export const CardLinks: string
export const cardLinks: string
export const CardIcon: string
export const cardIcon: string
export const CardIconThird: string
export const cardIconThird: string
export const CardBottom: string
export const cardBottom: string
export const CardTag: string
export const cardTag: string
export const isActive: string
export const skeletonShimmerAnimation: string
