export const Button: string
export const button: string
export const typeNav: string
export const typeLargeCTA: string
export const typeLargeCta: string
export const Link: string
export const link: string
export const typeFooter: string
export const skeletonShimmerAnimation: string
