export const Timeline: string
export const timeline: string
export const TimelineEnding: string
export const timelineEnding: string
export const Roadmap: string
export const roadmap: string
export const RoadmapContent: string
export const roadmapContent: string
export const RoadmapCircle: string
export const roadmapCircle: string
export const Before: string
export const before: string
export const During: string
export const during: string
export const Future: string
export const future: string
export const Last: string
export const last: string
export const skeletonShimmerAnimation: string
