export const QuoteBlock: string
export const quoteBlock: string
export const Selector: string
export const selector: string
export const SelectorDot: string
export const selectorDot: string
export const SelectorDotActive: string
export const selectorDotActive: string
export const skeletonShimmerAnimation: string
