export const GetStarted: string
export const getStarted: string
export const Core: string
export const core: string
export const Grid: string
export const grid: string
export const PubKey: string
export const pubKey: string
export const PubKeyWrap: string
export const pubKeyWrap: string
export const skeletonShimmerAnimation: string
