export const Intro: string
export const intro: string
export const IntroHeading: string
export const introHeading: string
export const Learn: string
export const learn: string
export const LearnBoxes: string
export const learnBoxes: string
export const LearnMore: string
export const learnMore: string
export const skeletonShimmerAnimation: string
